/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    EnResume: typeof import('./content/en/resume.md')['default']
    Github: typeof import('./src/components/Github.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    LangSwitch: typeof import('./src/components/LangSwitch.vue')['default']
    Layouts: typeof import('./src/components/Layouts.vue')['default']
    Mode: typeof import('./src/components/Mode.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ZhResume: typeof import('./content/zh/resume.md')['default']
  }
}
