// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Button: typeof import('./components/Button.vue')['default']
    FindLink: typeof import('./components/FindLink.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Rainy: typeof import('./components/Rainy.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Squares: typeof import('./components/Squares.vue')['default']
  }
}
